added sync-s3-Marketdeals cronJob to helm cron templates, added variables for sync-s3-Marketdeals cronJob
glifio/filecoin-chart pull request #45
Opened 2021-11-18 14:45 UTC by mur-me

Finally, placed sync-s3-Marketdeals in helm chart.
Additionally created one more key-value pair for `JWT_SPACE00_TOKEN` in `aws-s3-marketdeals` secret.

It is already working in cluster:
```
$ kubectl get cronjob sync-s3-marketdeals -n spacerace 
NAME                  SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
sync-s3-marketdeals   */10 * * * *   False     0        4m3s            15m
```

2021-11-18 16:05 UTC, ArseniiPetrovich requested changes
Everything looks good to me, but I'm thinking that it might be reasonable to have to files - one for crons connected to snapshots, and separate for s3deals, cuz it looks completely separate and does not depend on anything else on that file.

2021-11-18 16:08 UTC, mur-me commented
@ArseniiPetrovich it is not a problem at all, I'll separate them

2021-11-19 10:01 UTC, mur-me commented
> Everything looks good to me, but I'm thinking that it might be reasonable to have to files - one for crons connected to snapshots, and separate for s3deals, cuz it looks completely separate and does not depend on anything else on that file.

Moved to separate file

2021-11-19 10:41 UTC, ArseniiPetrovich approved these changes

2021-11-22 10:05 UTC, merged